#pragma once

#define MOD_NONSHARE_UART_CMD_INIT 0
#define MOD_NONSHARE_UART_CMD_PUT 1
#define MOD_NONSHARE_UART_CMD_GET 2
#define MOD_NONSHARE_UART_CMD_DESTORY 3
#define MOD_NONSHARE_UART_REG_ADDR 0x10010000
#define MOD_NONSHARE_UART_REG_SIZE 0x1000
